### PR TITLE
Small color changes

### PR DESCRIPTION
**Pull request by jemisonf**
Hello,

No need to merge this PR if it doesn't fit with your vision for the theme, but I wanted to submit it in case you were interested.

## Issue

I felt like the rouge background for the active tab was kind of distracting while using the editor. I decided to try changing the active tab color to the standard theme dark blue, while using the theme's lighter blue color used for active items in some other cases for inactive tabs.

## Changes:

* changes inactive tab background to lighter blue color
* changes active tab background to dark blue color
* changes color of inactive title bar to medium dark blue

## Screenshots

This is a screenshot of an inactive window. It should show basically all of the changes.

New:

Old:

### CODE REVIEW

**Comment by josefaidt** [comment]
👋 Hi @jemisonf ! Thanks for contributing! I'm going to take a look at your edits, I do really enjoy the contrast you've added, and may add it as its own sub-theme? Rouge Blue?

I haven't fully abandoned the original Rouge but I've been working on Rouge 2 for a hot minute. Would love to get your opinion on it!

**Comment by jemisonf** [comment]
Hey @josefaidt ,

Adding it as a separate sub-theme is a great idea. I could update the PR to do that instead if you'd like when I get a chance. I'd be happy to check out Rouge 2 although I'm pretty far from an expert on editor color themes.

**Comment by josefaidt** [comment]
Yes, whenever you get a chance, that's cool. Set it up as it's own JSON file in `src/themes` and run the build script to let Gulp remove comments (I change the language mode locally to JSONc so it doesn't scream at me for my comments). We can work on the name, too.

Rouge 2 is still in "alpha" meaning I'm making changes and running the theme full-time to test it out. I'm still learning about colors and such so I wouldn't consider myself an expert on them either 🙂. It is darker, even more flushed, a tad more "rouge", and is honestly best used at night. I'm thinking of making a vibrant variant to mitigate that issue, specifically. Really the changes are just too drastic to make it the official 2nd version, so it will also be a sub-theme.

All changes I'm doing are on the `2.0.0` branch. You can find the vsix [here](https://github.com/josefaidt/rouge-theme/blob/2.0.0/rouge-theme-2.0.0-alpha.17.vsix) and install it using 

```shell
code --install-extension rouge-theme-2.0.0-alpha.17.vsix
```

[kanban board](https://www.notion.so/josefaidt/26a18b5a350f4ddcae103c78e86034c6?v=e6834d0947554058a753679b221d5155)

If you have some ideas feel free to hack away, but I'd also like to get your overall opinion. There isn't a set timeline for the release so no rush.

**Comment by jemisonf** [comment]
Hey @josefaidt ,

Moved changes to rouge-quiet. I'll check out 2.0.0 when I get a chance--have been fairly busy as I'm sure you call tell from me taking 2 weeks to response to this :). Let me know if you have a preferred place for me to leave comments/thoughts/ etc.

**Comment by josefaidt** [comment]
@jemisonf hey, apologies for the delay, I'll check it out soon and publish. You can drop some thoughts here if you'd like. Or I'll open a 2.0 PR and do it there

**Comment by josefaidt** [comment]
woah @jemisonf so sorry I completely forgot about this. Kind of chilled out on 2 for a few months, but I saw this last night when I published 2. If you wouldn't mind copying it over to the new setup I'll build it and get it published!

**Comment by josefaidt** [comment]
hey @jemisonf I brought some of the changes over into #25, closing this in favor of tracking there.

**Pull request closed without merging**
